#!/usr/bin/env python3
"""Consolidate the completed exact-pair and jury-bootstrap campaigns.

This is deliberately a reporting layer. It does not combine uncertainty
components generated by different, non-joint resampling schemes.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np


DATA_DIR = Path(__file__).resolve().parents[1] / "data"
USER_JSON = DATA_DIR / "overnight_uncertainty_full.json"
JURY_JSON = DATA_DIR / "overnight_jury_bootstrap_full.json"
JURY_CHECKPOINT = DATA_DIR / "overnight_jury_bootstrap_full_checkpoint.npz"
OUT_JSON = DATA_DIR / "exact_estimator_consolidated.json"
OUT_REPORT = DATA_DIR / "EXACT_ESTIMATOR_CONSOLIDATED_REPORT.md"


def finite_median(values):
    values = np.asarray([v for v in values if v is not None], dtype=float)
    values = values[np.isfinite(values)]
    return None if not len(values) else float(np.median(values))


def main():
    user = json.loads(USER_JSON.read_text(encoding="utf-8"))
    jury = json.loads(JURY_JSON.read_text(encoding="utf-8"))
    user_by_id = {row["work_id"]: row for row in user["books"]}
    jury_by_id = {row["work_id"]: row for row in jury["books"]}
    if set(user_by_id) != set(jury_by_id):
        raise RuntimeError("completed campaigns track different candidate books")

    top200 = [
        row for row in user["books"]
        if row["exact_rank"] is not None and row["exact_rank"] <= 200
    ]
    matched = []
    for row in top200:
        other = jury_by_id[row["work_id"]]
        matched.append(
            {
                "work_id": row["work_id"],
                "title": row["title"],
                "author": row["author"],
                "rank": row["exact_rank"],
                "score": row["exact_score"],
                "reader_u80": row["bootstrap_u80"],
                "jury_u80": other["jury_boot_u80"],
                "reader_eligibility": row["bootstrap_eligible_rate"],
                "jury_eligibility": other["jury_boot_eligible_rate"],
            }
        )

    with np.load(JURY_CHECKPOINT, allow_pickle=False) as saved:
        completed = int(saved["completed"])
        inclusion = saved["selected_counts"].astype(float) / completed
    if not np.isclose(inclusion.sum(), 4929.0):
        raise RuntimeError("bootstrap inclusion mass does not equal hard jury size")

    paired_ratio = [
        row["jury_u80"] / row["reader_u80"]
        for row in matched
        if row["jury_u80"] is not None
        and row["reader_u80"] is not None
        and row["reader_u80"] > 0
    ]
    low_evidence = sorted(
        [
            row for row in matched
            if min(row["reader_eligibility"], row["jury_eligibility"]) < 0.8
        ],
        key=lambda row: min(row["reader_eligibility"], row["jury_eligibility"]),
    )
    result = {
        "meta": {
            "purpose": "consolidate exact-pair, reader-block, and jury-composition results",
            "exact_pair_replicates": user["meta"]["completed_replicates"],
            "jury_replicates": jury["meta"]["completed_replicates"],
            "n_candidates": len(user_by_id),
            "n_exact_rankable": user["meta"]["n_exact_rankable"],
        },
        "decision": {
            "production_pair_estimator": "exact expected inclusion M/H and M/L",
            "headline_uncertainty": "reader-block conditional u80",
            "additional_uncertainty": "jury-composition conditional u80",
            "combine_components": False,
            "reason": (
                "the campaigns were not a joint nested bootstrap; show both widths and both "
                "eligibility probabilities until joint calibration exists"
            ),
        },
        "top200_summary": {
            "n": len(matched),
            "median_reader_u80": finite_median(r["reader_u80"] for r in matched),
            "median_jury_u80": finite_median(r["jury_u80"] for r in matched),
            "median_jury_to_reader_u80_ratio": finite_median(paired_ratio),
            "reader_eligibility_below_80pct": int(sum(r["reader_eligibility"] < .8 for r in matched)),
            "jury_eligibility_below_80pct": int(sum(r["jury_eligibility"] < .8 for r in matched)),
        },
        "soft_jury_mass": {
            "n_broad_users": int(len(inclusion)),
            "total_mass": float(inclusion.sum()),
            "ever_selected": int(np.sum(inclusion > 0)),
            "selected_at_least_99pct": int(np.sum(inclusion >= .99)),
            "selected_at_most_1pct": int(np.sum(inclusion <= .01)),
            "ambiguous_10_to_90pct": int(np.sum((inclusion >= .10) & (inclusion <= .90))),
            "quantiles": {
                str(q): float(np.quantile(inclusion, q))
                for q in (0, .25, .5, .75, .9, .99, 1)
            },
        },
        "low_evidence_top200": low_evidence,
        "top200": matched,
    }
    OUT_JSON.write_text(
        json.dumps(result, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )

    s = result["top200_summary"]
    m = result["soft_jury_mass"]
    lines = [
        "# Consolidated exact estimator and uncertainty decision",
        "",
        "## Decision",
        "",
        "The exact expected-inclusion estimator replaces the arbitrary 12×12 hash sample. "
        "For a reader with H eligible 5-star and L eligible ≤3-star ratings, "
        "M=min(H,L,12), so each positive event receives M/H and each negative event M/L.",
        "",
        "Report reader-block `u80` as the primary conditional `±u`, jury-composition `u80` "
        "as a second uncertainty component, and both eligibility probabilities separately. "
        "Do not yet collapse the two widths into one number: the campaigns were not a joint "
        "nested bootstrap.",
        "",
        "## Completed evidence",
        "",
        f"- Reader-block replicates: **{result['meta']['exact_pair_replicates']:,}**; "
        f"jury-composition replicates: **{result['meta']['jury_replicates']:,}**.",
        f"- Exact rankable books: **{result['meta']['n_exact_rankable']:,}** from "
        f"**{result['meta']['n_candidates']:,}** tracked near-evidence candidates.",
        f"- Within the exact top 200, median reader `u80` is **{s['median_reader_u80']:.2f}** "
        f"points and median jury `u80` is **{s['median_jury_u80']:.2f}** points.",
        f"- Median jury/reader width ratio is **{s['median_jury_to_reader_u80_ratio']:.3f}**. "
        "Reader sampling/evidence is therefore the larger uncertainty axis at present.",
        f"- Top-200 books below 80% eligibility: **{s['reader_eligibility_below_80pct']}** "
        f"under reader resampling and **{s['jury_eligibility_below_80pct']}** under jury refits.",
        "",
        "## Soft-jury implication",
        "",
        f"Bootstrap inclusion probabilities preserve exactly **{m['total_mass']:.0f}** juror "
        f"equivalents across {m['n_broad_users']:,} candidates. **{m['selected_at_least_99pct']:,}** "
        f"users are selected in at least 99% of refits, **{m['selected_at_most_1pct']:,}** in at "
        f"most 1%, and only **{m['ambiguous_10_to_90pct']:,}** occupy the 10–90% boundary band. "
        "This supports a controlled soft-boundary ablation rather than a wholesale latent-jury rewrite.",
        "",
        "## Interpretation",
        "",
        "Eligibility is part of uncertainty, not a nuisance to hide. A high conditional score "
        "with low eligibility remains an underexposed candidate. Γ sensitivity for unobserved "
        "enthusiast selection remains a separate systematic-bias trajectory and is not included "
        "in either `u80`.",
        "",
    ]
    OUT_REPORT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_REPORT}")


if __name__ == "__main__":
    main()
